competition_name: digit-recognizer
task: classification
target_column: label
id_column: ImageId

# Features will be auto-detected in train.py (pixel0..pixel783)
features:
  numeric: [] 
  categorical: []

model:
  name: mlp
  params:
    hidden_layer_sizes: [100]
    activation: relu
    solver: adam
    max_iter: 200
    early_stopping: True
    validation_fraction: 0.1
    random_state: 42
    multiclass_strategy: ovr # Use One-vs-Rest strategy

cv:
  n_splits: 3
  scoring: accuracy
